name: Azure Example Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/CLI@v1
        with:
          azcliversion: latest

      - name: Login via Azure CLI
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CRED }}
        run: echo "${AZURE_CREDENTIALS}" > azure_credentials.json

      - name: Azure CLI script example
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az login --service-principal --username $(jq -r .clientId < azure_credentials.json) --password $(jq -r .clientSecret < azure_credentials.json) --tenant $(jq -r .tenantId < azure_credentials.json)
            az storage account show --name <storage_account_name> --resource-group <resource_group_name> --output table
