name: Azure Example Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Azure CLI
        uses: azure/CLI@v1
        with:
          azcliversion: latest

      - name: Login via Azure CLI
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CRED }}
        run: |
          echo "$AZURE_CREDENTIALS" | az login --service-principal -u http://azure-cli-2024 -p /dev/stdin --tenant <tenant_id>