name: Azure CLI Login

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/cli@v1

    - name: Log in to Azure
      run: az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Set subscription
      run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Verify login
      run: az account show
