name: Azure Example Workflow

# This workflow triggers on every push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner with Node.js 20

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Log in to Azure using the service principal credentials stored in GitHub secrets
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CRED }}

      # Step 3: Set up kubectl to interact with the Kubernetes cluster
      - name: Setup kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      # Step 4: Retrieve AKS credentials to configure kubectl
      - name: Retrieve AKS Credentials
        run: az aks get-credentials --resource-group Sysdig-RG --name sysdig-demo

      # Step 5: List the nodes in the AKS cluster to verify the connection
      - name: List AKS Nodes
        run: kubectl get nodes

      # Step 6: Install Sysdig CLI
      - name: Install Sysdig CLI
        run: |
          curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/linux/amd64/sysdig-cli-scanner"
          chmod +x ./sysdig-cli-scanner
      
      # Step 7: Pull Docker image
      - name: Pull Docker image
        run: docker pull dockersamples/examplevotingapp_vote:latest

      # Step 8: Scan Docker image with Sysdig
      - name: Scan Docker image with Sysdig
        run: |
          SECURE_API_TOKEN=cc1ee15e-0fd8-41d3-8829-37e3c881b2e3 ./sysdig-cli-scanner --apiurl https://app.us4.sysdig.com pull://dockersamples/examplevotingapp_vote:latest

      # Step 9: Deploy the resources defined in the Kubernetes manifest files (Commented out)
      # - name: Deploy Resources to AKS
      #   run: kubectl apply -f k8s-specifications/

      # Step 10: Promote to production or perform additional steps
      - name: Promote to Production
        run: |
          # Example: Switch traffic or perform post-deployment tasks
          echo "Promoting to production..."
