name: Azure Example Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CRED }}

      - name: Setup up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'
      
      - name: Get AKS credentials
        run: az aks get-credentials --resource-group Sysdig-RG --name  sysdig-demo
      
      - name: Get AKS nodes
        run: kubectl get nodes